apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
  namespace: {{ .Values.namespace}}
spec:
  type: {{ .Values.bankapp.service.type}}
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: bankapp   