namespace: mahendra

mysql:
  password: Test@123
  databasename: bankappdb
  region: us-east-1a  
  image: mysql:8

persistentvolume:
  storage: 5Gi
  storageclassname: mysql-data 
  volumehandle: vol-0f86a15e5511e56c9

resources:
  mysql:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1Gi
      cpu: 1      
            
bankapp:
  image: 1mahendra/bankapp:v12
  replicas: 2
  service:
    type: LoadBalancer          
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 500Mi
      cpu: 500m
